name: Attach memcard_pro_renamer.py to release
on:
  release:
    types: [published]
jobs:
  attach_py:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Upload memcard_pro_renamer.py to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: memcard_pro_renamer.py
          asset_name: memcard_pro_renamer.py
          tag: ${{ github.ref }}
          overwrite: true
